#!/usr/bin/env python3
import os
import sys
import inspect
import importlib
from pathlib import Path

def list_dirs(path):
    for file in os.listdir(path):
        if file == '__pycache__': continue
        print(file.rstrip(".py"))

if __name__ == "__main__":
    pwd = 'cli/'
    args = sys.argv[1:]

    if len(args) == 0:
        list_dirs(pwd)
        sys.exit()

    i = 1
    for arg in args:
        path = pwd + arg
        rest = args[i:]
        
        if os.path.isfile(path + '.py'):
            module = importlib.import_module(path.replace('/', '.'))
            
            if len(rest) == 0:
                funcs = [name for name in dir(module) if inspect.isfunction(getattr(module, name))]
                for func in funcs:
                    print(func)
                break

            if hasattr(module, rest[0]):
                func = getattr(module, rest[0])
                if callable(func): func(*rest[1:])

        if os.path.isdir(path):
            if len(rest) == 0:
                list_dirs(path)
            pwd = path + '/'
    i += 1
    # create_all();
